### ISSUE TITLE
学会使用git，完成操作任务

### ISSUE THREAD

**Issue by gaoyuyue** [attackme/task#1]
## 操作任务:
- 在组织下新建以自己英文名字命名的仓库，初始化readme文件并写入自己的中文名字。
- 克隆仓库到本地，向本地仓库中添加文件(自己写的一段源程序不限语言)，提交并推送到远程github仓库。
# 任务截至时间：9月27号中午12点 ！！！！！！！！

**Comment by FreakLign** [comment]
Ok,All right

**Comment by Annewufit** [comment]
OK

**Comment by gaoyuyue** [comment]
# 任务截至时间：9月27号中午12点 ！！！！！！！！
